routes/web.php
<?php

use Illuminate\Support\Facades\Route;

 
use App\Http\Controllers\PublicController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\PublicProductController;
use App\Http\Controllers\PublicPageController;
use App\Http\Controllers\PublicProductDetailsController;
use App\Http\Controllers\PublicAuthController;
use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\SellbookController;
use App\Http\Controllers\RequestbookController;
use App\Http\Controllers\DonatebookController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CarouselController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';


//This is frontend route
Route::controller(PublicController::class)->group(function(){
    Route::get('/home','home')->name('homepage');

});

Route::controller(PublicProductController::class)->group(function(){
         
    Route::get('/bestbook','bestbook')->name('bestbook'); 
    Route::get('/newcollection','newcollection')->name('newcollection'); 
    Route::get('/oldbook','oldbook')->name('oldbook');
    Route::get('/getdonate','getdonate')->name('getdonate');
    Route::get('/earnpoint','earnpoint')->name('earnpoint');
});


Route::controller(PublicPageController::class)->group(function(){
    Route::get('/aboutus','aboutus')->name('aboutus'); 
    Route::get('/contactus','contactus')->name('contactus'); 
    Route::get('/faq','faq')->name('faq'); 
    Route::get('/events','events')->name('events'); 

});


Route::controller(PublicProductDetailsController::class)->group(function(){
    Route::get('/bookdetails/{bookdetail}','bookdetails')->name('bookdetails'); 
    Route::get('/cart/{cart}','cart')->name('cart'); 
    Route::get('/payment/{pay}','payment')->name('payment'); 
  

});


    Route::resource('sellbooks', SellbookController::class);
    Route::resource('donatebooks', DonatebookController::class);
    Route::resource('requestbooks', RequestbookController::class);
    Route::resource('users', UserController::class);
    Route::resource('carousels', CarouselController::class);

    Route::get('/user',[UserController::class,'user'])->name('user.register'); 

 
 
    Route::middleware('auth')->controller(AdminController::class)->prefix('admin')->group(function(){
        Route::get('/dashboard','dashboard')->name('admin.dashboard');
        Route::get('/productlist','productlist')->name('admin.productlist'); 
        
    
}
);
 

 

resources/views/backend/adminrequestbook/edit.blade.php
<x-backend.layout.master title="Request Book" bottomheader="Request Book">
    
    <div class="container card w-50 ">
        <form class="form-horizontal" role="form" action="{{ route('requestbooks.update',['requestbook'=>$requestbookedit->id]) }}" method="post" enctype="multipart/form-data">
           @csrf
           @method('patch')
          
            <div class="card-header bg-info"> <h2 class="text-center mt-2"></h2>Request Book</div>
            <br>
            <x-backend.alertmessage.alertmessage type="success"/>
        
            <x-frontend.form.input name="booktitle" text="Book Title" type="text" :value="old('booktitle', $requestbookedit->booktitle)"/>
    
            <x-frontend.form.input name="bookauthor" text="Book Author" type="text" :value="old('bookauthor', $requestbookedit->bookauthor)"/>
            
            <x-frontend.form.input name="bookedition" text="Book Edition" type="text" :value="old('bookedition', $requestbookedit->bookedition)"/>
            <x-frontend.form.input name="bookquantity" text="Book Quantity" type="text" :value="old('bookquantity', $requestbookedit->bookquantity)"/>
           
           
            
            <x-frontend.form.input name="mobile" text="Mobile" type="tel" pattern="[0-9]{11}" :value="old('mobile', $requestbookedit->mobile)"/>
           
            <x-frontend.form.input name="address" text="Address" type="text" :value="old('address', $requestbookedit->address)"/>
       
          <button type="submit" class="btn btn-success d-flex">Update</button>
               
      
            </div> 
        
        </form>   
       
      </div>

</x-backend.layout.master>








 

resources/views/backend/adminrequestbook/requestbooklist.blade.php
<x-backend.layout.master>
    @slot('title')
   Request Book
    @endslot
<div class="card mb-4">
    @slot('bottomheader')
  Request Book
    @endslot
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
       Request Book
       <a href="{{ route('requestbooks.create') }}"> <button class="btn btn-info">Add Product</button></a>
    </div>
   <x-backend.alertmessage.alertmessage type="success"/>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>SL No</th>
                    <th>Book Title</th>
                    <th>Book Author</th>
                    <th>Book Edition</th>
                    <th>Book Quantity</th>
                    <th>Address</th>
                    <th>Mobile</th>
                   
                </tr>
            </thead>
           
            <tbody>
                @foreach ($requestbooklist as $requestbooklist)
                    
               
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $requestbooklist->booktitle }}</td>
                    <td>{{ $requestbooklist->bookauthor }}</td>
                    <td>{{ $requestbooklist->bookedition }}</td>
                    <td>{{ $requestbooklist->bookquantity}}</td>
                    <td>{{ $requestbooklist->address }}</td>
                    <td>{{ $requestbooklist->mobile }}</td>
                     
                  
                     
                    <td>
                        <div class="d-flex">
                            {{-- <x-backend.buttonlink.viewlink root="donatebook.show" id="{{ $donatebooklist->id }}" idname="donatebook"/>
                            <x-backend.buttonlink.editlink root="donatebook.edit" id="{{ $donatebooklist->id }}" idname="donatebook"/>
                            <x-backend.buttonlink.deletelink root="donatebook.destroy" id="{{ $donatebooklist->id }}" idname="donatebook"/> --}}
                             
                            <x-backend.buttonlink.viewlink href="{{ route('requestbooks.show',['requestbook'=>$requestbooklist->id ])}}"/>
                            <x-backend.buttonlink.editlink href="{{ route('requestbooks.edit',['requestbook'=>$requestbooklist->id ])}}"/>
                            <x-backend.buttonlink.deletelink action="{{ route('requestbooks.destroy',['requestbook'=>$requestbooklist->id ])}}"/>
                        </div>
  
                         {{-- <a href="{{ route('sellbook.show',[
                            'sellbook'=>$sellbooklist->id
                         ]) }}">
                            <i class="fa-solid fa-pencil text-success"style="margin-left:20px"></i>
                        </a> --}}
                     {{-- <form action="{{ route('sellbook.destroy',['sellbook'=>$sellbooklist->id] )}}" method="POST">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn text-danger d-inline" onclick="confirm('Are you Sure?')"><i class="fa-solid fa-trash-can"></i></button>
                       

                     </form> --}}
                        

                    </td>
                </tr>
                @endforeach
            </tbody>
            
        </table>
      
    </div>
</div>
b
</x-backend.layout.master>

resources/views/backend/adminrequestbook/show.blade.php
 
    <x-backend.layout.master>
        @slot('title')
        Book Details
        @endslot
    <div class="card mb-4">
        @slot('bottomheader')
       Book Details
        @endslot
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Book Details
           <a href="{{ route('donatebooks.create') }}"> <button class="btn btn-sm btn-info">ADD BOOK</button></a>
        </div>
      
        <div class="card w-50 mx-auto mt-4">
            <div class="card-header text-center">
              <b> Book Details</b>
            </div>
            
            <address class="m-5 mx-auto">
              Book Title :{{ $requestbookshow->booktitle}} <br>
              Book Author: {{ $requestbookshow->bookauthor }} <br>
              Book Edition: {{ $requestbookshow->bookedition }} <br>
              Mobile: {{ $requestbookshow->mobile }} <br>
            </address>
          </div>
    </div>
     
    </x-backend.layout.master>
 
 
 

resources/views/backend/adminrequestbook/update.blade.php
<x-backend.layout.master title="Donatebook" bottomheader="Update Donate Book">
    
<div class="container card w-50">
    <form class="form-horizontal" role="form" action="{{ route('donatebooks.update',['donatebook'=>$donatebookedit->id]) }}" method="post" enctype="multipart/form-data">
        @csrf 
        @method('patch')
        <h2 class="text-center">Donate Book</h2>
            <br> <br><br>
    
            {{-- use components --}}
                <x-frontend.form.input name="fullname" text="Full Name" type="text" :value="old('fullname', $donatebookedit->fullname)" />
                <x-frontend.form.input name="email" text="Email" type="text" :value="old('email', $donatebookedit->email)" />
                <x-frontend.form.input name="address" text="Address" type="text" :value="old('address', $donatebookedit->address)"/>
                <x-frontend.form.input name="mobile" text="Mobile" type="tel" pattern="[0-9]{11}" :value="old('mobile', $donatebookedit->mobile)"/>
                <x-frontend.form.input name="booktitle" text="Book Title" type="text" :value="old('booktitle', $donatebookedit->booktitle)"/>
                <x-frontend.form.input name="bookauthor" text="Book Author" type="text" :value="old('bookauthor', $donatebookedit->bookauthor)"/>
                <x-frontend.form.input name="bookedition" text="Book Edition" type="text" :value="old('bookedition', $donatebookedit->bookedition)"/>
            
              <div class="form-group" style="padding-left: 20px; color: gray;">
                  <button type="submit" class="btn btn-primary" name="submit">Submit</button>
              </div>       
        
        </form>  <!-- /form -->
    </div>
 
</x-backend.layout.master>








 