routes/web.php
<?php

use Illuminate\Support\Facades\Route;

 
use App\Http\Controllers\PublicController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\PublicProductController;
use App\Http\Controllers\PublicPageController;
use App\Http\Controllers\PublicProductDetailsController;
use App\Http\Controllers\PublicAuthController;
use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\SellbookController;
use App\Http\Controllers\RequestbookController;
use App\Http\Controllers\DonatebookController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CarouselController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';


//This is frontend route
Route::controller(PublicController::class)->group(function(){
    Route::get('/home','home')->name('homepage');

});

Route::controller(PublicProductController::class)->group(function(){
         
    Route::get('/bestbook','bestbook')->name('bestbook'); 
    Route::get('/newcollection','newcollection')->name('newcollection'); 
    Route::get('/oldbook','oldbook')->name('oldbook');
    Route::get('/getdonate','getdonate')->name('getdonate');
    Route::get('/earnpoint','earnpoint')->name('earnpoint');
});


Route::controller(PublicPageController::class)->group(function(){
    Route::get('/aboutus','aboutus')->name('aboutus'); 
    Route::get('/contactus','contactus')->name('contactus'); 
    Route::get('/faq','faq')->name('faq'); 
    Route::get('/events','events')->name('events'); 

});


Route::controller(PublicProductDetailsController::class)->group(function(){
    Route::get('/bookdetails/{bookdetail}','bookdetails')->name('bookdetails'); 
    Route::get('/cart/{cart}','cart')->name('cart'); 
    Route::get('/payment/{pay}','payment')->name('payment'); 
  

});


    Route::resource('sellbooks', SellbookController::class);
    Route::resource('donatebooks', DonatebookController::class);
    Route::resource('requestbooks', RequestbookController::class);
    Route::resource('users', UserController::class);
    Route::resource('carousels', CarouselController::class);

    Route::get('/user',[UserController::class,'user'])->name('user.register'); 

 
 
    Route::middleware('auth')->controller(AdminController::class)->prefix('admin')->group(function(){
        Route::get('/dashboard','dashboard')->name('admin.dashboard');
        Route::get('/productlist','productlist')->name('admin.productlist'); 
        
    
}
);
 

 

resources/views/backend/adminsellbook/edit.blade.php
<x-backend.layout.master title="Sellbook" bottomheader="Update Sell Book">

    <div class="container card w-50 ">
        <form class="form-horizontal" role="form" action="{{ route('sellbook.update',['sellbook'=>$sellbookedit->id]) }}" method="post" enctype="multipart/form-data">
           @csrf
           @method('patch')
            <div class="card-header bg-info"> <h2 class="text-center mt-2"></h2>Sell Book</div>
            <br>
           <x-backend.alertmessage.alertmessage type="success"/>
            <br>
            <br>
            <x-frontend.form.input name="booktitle" text="Book Tile" type="text" :value="old('booktitle', $sellbookedit->booktitle)" />
        
            <x-frontend.form.input name="bookauthor" text="Book Author" type="text" :value="old('bookauthor', $sellbookedit->bookauthor)" />
            <x-frontend.form.input name="bookedition" text="Book Edition" type="text" :value="old('bookauthor', $sellbookedit->bookedition)" />
            <x-frontend.form.input name="bookquantity" text="Book Quantity" type="text" :value="old('bookquantity', $sellbookedit->bookquantity)" />
            <x-frontend.form.input name="price" text="Price" type="text" :value="old('price', $sellbookedit->price)" />
            <x-frontend.form.input name="mobile" text="Mobile" type="text" :value="old('mobile', $sellbookedit->mobile)" />

            
                
                 
          <button type="submit" class="btn btn-success d-flex">Update</button>
               
      
      
      
      
      
            </div> 
            
                
        
        </form>   
       
      </div>
         



 

</x-backend.layout.master>

resources/views/backend/adminsellbook/sellbooklist.blade.php
<x-backend.layout.master>
    @slot('title')
    Sellbook
    @endslot
<div class="card mb-4">
    @slot('bottomheader')
   Sell Book
    @endslot
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Sell Book
       <a href="{{ route('sellbooks.create') }}"> <button class="btn btn-info">Add Product</button></a>
    </div>
   <x-backend.alertmessage.alertmessage type="success"/>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>SL No</th>
                    <th>Book Title</th>
                    <th>Book Author</th>
                    <th>Book Edition</th>
                    <th>Book Quantity</th>
                    <th>Price</th>
                    <th>Mobile</th>
                    <th>Action</th>
                </tr>
            </thead>
            {{-- <tfoot>
                <tr>
                    <th>Name</th>
                    <th>Position</th>
                    <th>Office</th>
                    <th>Age</th>
                    <th>Start date</th>
                    <th>Salary</th>
                    
                </tr>
            </tfoot> --}}
            <tbody>
                @foreach ($sellbooklist as $sellbooklist)
                    
               
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $sellbooklist->booktitle }}</td>
                    <td>{{ $sellbooklist->bookauthor }}</td>
                    <td>{{ $sellbooklist->bookedition }}</td>
                    <td>{{ $sellbooklist->bookquantity }}</td>
                    <td>{{ $sellbooklist->price }}</td>
                    <td>{{ $sellbooklist->mobile }}</td>
                    <td><img src="{{asset('/storage/sellbooks/'.$sellbooklist->bookimage)}}" alt="" style="width:50px;height:50px"></td>
                    <td>
                        <div class="d-flex">
                            <x-backend.buttonlink.viewlink  href="{{ route('sellbooks.show',['sellbook'=>$sellbooklist->id ])}}"/>
                            <x-backend.buttonlink.editlink href="{{ route('sellbooks.edit',['sellbook'=>$sellbooklist->id ])}}"/>
                           
                                <x-backend.buttonlink.deletelink action="{{ route('sellbooks.destroy',['sellbook'=>$sellbooklist->id ])}}"/>
                        </div>
                        
                
                        

                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
       
    </div>
</div>
 
</x-backend.layout.master>

resources/views/backend/adminsellbook/show.blade.php
 
    <x-backend.layout.master>
        @slot('title')
        Book Details
        @endslot
    <div class="card mb-4">
        @slot('bottomheader')
       Book Details
        @endslot
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Book Details
           <a href=""> <button class="btn btn-sm btn-info">ADD BOOK</button></a>
        </div>
      
        <div class="card w-50 mx-auto mt-4">
            <div class="card-header text-center">
              <b> Book Details</b>
            </div>
            <address class="m-5">
              Book Title :{{ $sellbookshow->booktitle }} <br>
              Book Author: {{ $sellbookshow->bookauthor }} <br>
              Book Edition: {{ $sellbookshow->bookedition }} <br>
              Book Price: {{ $sellbookshow->price }} <br>
              Mobile: {{ $sellbookshow->mobile }} <br>
            </address>
          </div>
    </div>
     
    </x-backend.layout.master>
 
 
 

resources/views/backend/adminsellbook/update.blade.php
<x-backend.layout.master title="Donatebook" bottomheader="Update Donate Book">
    
<div class="container card w-50">
    <form class="form-horizontal" role="form" action="{{ route('donatebooks.update',['donatebook'=>$donatebookedit->id]) }}" method="post" enctype="multipart/form-data">
        @csrf 
        @method('patch')
        <h2 class="text-center">Donate Book</h2>
            <br> <br><br>
    
            {{-- use components --}}
                <x-frontend.form.input name="fullname" text="Full Name" type="text" :value="old('fullname', $donatebookedit->fullname)" />
                <x-frontend.form.input name="email" text="Email" type="text" :value="old('email', $donatebookedit->email)" />
                <x-frontend.form.input name="address" text="Address" type="text" :value="old('address', $donatebookedit->address)"/>
                <x-frontend.form.input name="mobile" text="Mobile" type="tel" pattern="[0-9]{11}" :value="old('mobile', $donatebookedit->mobile)"/>
                <x-frontend.form.input name="booktitle" text="Book Title" type="text" :value="old('booktitle', $donatebookedit->booktitle)"/>
                <x-frontend.form.input name="bookauthor" text="Book Author" type="text" :value="old('bookauthor', $donatebookedit->bookauthor)"/>
                <x-frontend.form.input name="bookedition" text="Book Edition" type="text" :value="old('bookedition', $donatebookedit->bookedition)"/>
            
              <div class="form-group" style="padding-left: 20px; color: gray;">
                  <button type="submit" class="btn btn-primary" name="submit">Submit</button>
              </div>       
        
        </form>  <!-- /form -->
    </div>
 
</x-backend.layout.master>








 