routes/web.php
<?php

use Illuminate\Support\Facades\Route;

 
use App\Http\Controllers\PublicController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\PublicProductController;
use App\Http\Controllers\PublicPageController;
use App\Http\Controllers\PublicProductDetailsController;
use App\Http\Controllers\PublicAuthController;
use App\Http\Controllers\AdminAuthController;
use App\Http\Controllers\SellbookController;
use App\Http\Controllers\RequestbookController;
use App\Http\Controllers\DonatebookController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CarouselController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';


//This is frontend route
Route::controller(PublicController::class)->group(function(){
    Route::get('/home','home')->name('homepage');

});

Route::controller(PublicProductController::class)->group(function(){
         
    Route::get('/bestbook','bestbook')->name('bestbook'); 
    Route::get('/newcollection','newcollection')->name('newcollection'); 
    Route::get('/oldbook','oldbook')->name('oldbook');
    Route::get('/getdonate','getdonate')->name('getdonate');
    Route::get('/earnpoint','earnpoint')->name('earnpoint');
});


Route::controller(PublicPageController::class)->group(function(){
    Route::get('/aboutus','aboutus')->name('aboutus'); 
    Route::get('/contactus','contactus')->name('contactus'); 
    Route::get('/faq','faq')->name('faq'); 
    Route::get('/events','events')->name('events'); 

});


Route::controller(PublicProductDetailsController::class)->group(function(){
    Route::get('/bookdetails/{bookdetail}','bookdetails')->name('bookdetails'); 
    Route::get('/cart/{cart}','cart')->name('cart'); 
    Route::get('/payment/{pay}','payment')->name('payment'); 
  

});


    Route::resource('sellbooks', SellbookController::class);
    Route::resource('donatebooks', DonatebookController::class);
    Route::resource('requestbooks', RequestbookController::class);
    Route::resource('users', UserController::class);
    Route::resource('carousels', CarouselController::class);

    Route::get('/user',[UserController::class,'user'])->name('user.register'); 

 
 
    Route::middleware('auth')->controller(AdminController::class)->prefix('admin')->group(function(){
        Route::get('/dashboard','dashboard')->name('admin.dashboard');
        Route::get('/productlist','productlist')->name('admin.productlist'); 
        
    
}
);
 

 

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

public function profile()
{
    return $this->hasOne(profile::class);
}
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\user;

class UserController extends Controller
{
   
public function index()
{
  

    
    $users=User::all();
    return view('backend.user.userlist',[
        'users'=>$users
    ]);
}


public function show($user)
{

  
 $usershow=User::findOrFail($user);
 return view('backend.user.show',compact('usershow'));
     
 }
public function edit($user)
{
      
      $useredit=User::findOrFail($user);
      return view('backend.user.edit',compact('useredit'));  
}
 
  public function update(Request $request,$user)
 {
       $userupdate=User::findOrFail($user);
       $userupdate->update([
         'name'=>$request->name,
         'email'=>$request->email,
         
        ]
        );
        return redirect()->route('users.index')->withMessage('Successfully updated');
       
 }

public function destroy($user)
{
      $user=User::findOrFail($user)->delete();
      return redirect()->route('users.index')->withMessage('Successfully Data Deleted');       
}
public function user()
{
      return view('auth.register');
}
     


}

resources/views/backend/user/edit.blade.php
<x-backend.layout.master title="user" bottomheader="Update user">

    <div class="container card w-50 ">
        <form class="form-horizontal" role="form" action="{{ route('users.update',['user'=>$useredit->id]) }}" method="post" enctype="multipart/form-data">
           @csrf
           @method('patch')
            <div class="card-header bg-info"> <h2 class="text-center mt-2"></h2>User</div>
            <br>
           <x-backend.alertmessage.alertmessage type="success"/>
            <br>
            <br>
            <x-frontend.form.input name="name" text="User" type="text" :value="old('name', $useredit->name)" />
            <x-frontend.form.input name="email" text="Email" type="email" :value="old('email', $useredit->email)" />
        
     
                
                 
          <button type="submit" class="btn btn-success d-flex">Update</button>
               
      
      
      
      
      
            </div> 
            
                
        
        </form>   
       
      </div>
         



 

</x-backend.layout.master>

resources/views/backend/user/show.blade.php
 
    <x-backend.layout.master>
        @slot('title')
        User Details
        @endslot
    <div class="card mb-4">
        @slot('bottomheader')
      User Details
        @endslot
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
           Usert Details
           <a href="{{ route('sellbook') }}"> <button class="btn btn-sm btn-info">ADD BOOK</button></a>
        </div>
      
        <div class="card w-50 mx-auto mt-4">
            <div class="card-header text-center">
              <b> User Details</b>
            </div>
            <address class="m-5">
              User Name :{{ $usershow->name }} <br>
              User Email: {{ $usershow->email }} <br>
             
            </address>
          </div>
    </div>
     
    </x-backend.layout.master>
 
 
 

resources/views/backend/user/userlist.blade.php
<x-backend.layout.master>
    @slot('title')
     User List
    @endslot
<div class="card mb-4">
    @slot('bottomheader')
  User List
    @endslot
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        UserList
       <a href="{{ route('user.register') }}"> <button class="btn btn-info">Add User</button></a>
    </div>
   <x-backend.alertmessage.alertmessage type="success"/>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>SL No</th>
                    <th>Name</th>
                    <th>Email</th>
                   
                    <th>Created_at</th>
                    <th>Updated_at</th>
                    <th>Action</th>
                     
                </tr>
            </thead>
           
            <tbody>
                @foreach ($users as $user)
                    
               
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->created_at }}</td>
                    <td>{{ $user->updated_at }}</td>
                     
                     <td>
                        <div class="d-flex">
                        <x-backend.buttonlink.viewlink href="{{ route('users.show',['user'=>$user->id ])}}"/>
                        <x-backend.buttonlink.editlink href="{{ route('users.edit',['user'=>$user->id ])}}"/>
               
                        <x-backend.buttonlink.deletelink action="{{ route('users.destroy',['user'=>$user->id ])}}"/>
                        </div>
                    </td>
                         {{-- <a href="{{ route('sellbook.show',[
                            'sellbook'=>$sellbooklist->id
                         ]) }}">
                            <i class="fa-solid fa-pencil text-success"style="margin-left:20px"></i>
                        </a> --}}
                     {{-- <form action="{{ route('sellbook.destroy',['sellbook'=>$sellbooklist->id] )}}" method="POST">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn text-danger d-inline" onclick="confirm('Are you Sure?')"><i class="fa-solid fa-trash-can"></i></button>
                       

                     </form> --}}
                        

                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
 
</x-backend.layout.master>